version: '3.8'
services:
  # console credentials
  # minioadmin:minioadmin
  minio:
    image: minio/minio:RELEASE.2022-03-24T00-43-44Z
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"
