version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.0

    working_directory: /go/src/github.com/ymgyt/cloudops

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run: go get github.com/golang/dep/cmd/dep 

      - restore_cache:
          keys:
            - deps-cache-{{ checksum "Gopkg.lock" }}

      - run: dep ensure

      - save_cache:
          key: deps-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - "vendor"

      - run: make test | tee ${TEST_RESULTS}/go-test.out
